### ISSUE TITLE
Add cross platform features

### ISSUE THREAD

**Issue by winginitau** [stevemarple/IniFile#13]
Hi Steve, are you still maintaining and/or updating this library - I see no commits for 6 months?

After doing some searching, your library seems like exactly what I'm looking for - surprised that there are no contributors - thoughts? Better solution elsewhere?

I'm a newbie to arduino (and haven't coded for 25 years), so still on the learning curve (and what I remember of C coding is rusty.....

Wondering if its worth extending your library to handle different platforms? I think the logic of the library seems sound though in the first instance I'd like to pass a file pointer to the constructor that is generic (arduino SD File (regardless of SD library used) or linux gcc FILE) rather than a filename.

Would this be something easy to implement?

Many thanks,
Brendan

**Comment by stevemarple** [comment]
The library is aimed towards Arduino usage. There is an Arduino compatibility header in the tests folder which is used to allow development in a Linux environment.
