### ISSUE TITLE
parse missing key error occur

### ISSUE THREAD

**Issue by zhuxiaoyou2011qp** [stevemarple/IniFile#18]
>>>>>>
A.ini
[A]
a=1
[B]
b=1
>>>>>>
then we getValue("A","b",buffer,len) == true

in src/IniFile.cpp line 140: if (getValue(section, key, buffer, len) < 0) need changed to: if (getValue(section, key, buffer, len) == false),because line 92: bool IniFile::getValue(const char* section, const char* key,...) returns bool,but not int.same as in line 160,170,190,214,248

**Comment by stevemarple** [comment]
Fixed in `v1.0.4`.
