### ISSUE TITLE
Inline comments

### ISSUE THREAD

**Issue by OscarVanL** [stevemarple/IniFile#20]
Hi, I noticed inline comments are not permitted.

This doesn't work:

`testFrequency=60 # How frequently the test should be conducted, in seconds`

Whereas this does:

```
# How frequently the test should be conducted, in seconds
testFrequency=60 
```

I'd love to be able to use the former as I think it looks neater.

**Comment by stevemarple** [comment]
Inline comments are not supported as that would prevent the `#` or `;` character being used in the value string.

**Comment by OscarVanL** [comment]
Fair enough, thanks :)
