### ISSUE TITLE
Support Double variables types for getValue

### ISSUE THREAD

**Issue by OscarVanL** [stevemarple/IniFile#21]
I find it useful that getValue allows for a fifth argument for the variable to store the read value into, however, noticed it lacked the support for 'double' types. Would it be possible to add this, or is there an intentional decision for omitting this type?

**Comment by stevemarple** [comment]
It was just an omission. Thanks for your commit 580a4ae3fbc92999c79419e794f4c5b76ff2842a which adds this support.

**Comment by OscarVanL** [comment]
Thank you, I suspected this may have been the case. Thank you for merging it! :)

By the way - this library has been very useful for a fairly complex project I'm working on with tens of user configurable options of many types, yet it's been a breeze to use. Appreciate your hard work.
