### ISSUE TITLE
Slight modification to handle SD_MMC connections

### ISSUE THREAD

**Issue by HankLloydRight** [stevemarple/IniFile#35]
Hi,

 Great lib, thank you! 

 I'm using SD_MMC instead of SD/SPI, and in order to get this lib to work, I had to change two lines:

Line 10: `#include <SD_MMC.h>`
Line 158: `_file = SD_MMC.open(_filename, _mode);`

And then the repository works perfectly with SD_MMC connections.

**Comment by stevemarple** [comment]
If the Arduino IDE allowed programmers to externally define macros it would be possible for `IniFile` to include the appropriate header files and use the correct open function. Despite asking, and submitting a pull-request to support it (https://github.com/arduino/arduino-builder/pull/29), the IDE developers repeatedly refuse to include such a feature, which makes adding this kind of support difficult.
