### ISSUE TITLE
Delete contents

### ISSUE THREAD

**Issue by ADJ7WTB** [stevemarple/IniFile#37]
Very weird problem. I added setings in the data file. Upload the code but reads nothing from the file. Open file on PC and the content is missing. Some how the data gets deleted.

**Comment by stevemarple** [comment]
The IniFile object can (and should) be created with the file mode set to read. That will prevent IniFile from writing to the file.

**Comment by ADJ7WTB** [comment]
Thanks. Problem is that is cleared the file completely.

**Comment by stevemarple** [comment]
IniFile only requires read so set the mode to read. Opening an existing file with write mode (not append) will truncate the file.
